// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/royal-denture/HeroHeader.tsx": () => import("../components/mockups/royal-denture/HeroHeader.tsx"),
  "./components/mockups/royal-denture/MobileOrderFlow.tsx": () => import("../components/mockups/royal-denture/MobileOrderFlow.tsx"),
  "./components/mockups/royal-denture/ProductCards.tsx": () => import("../components/mockups/royal-denture/ProductCards.tsx")
};
